Limit chroot use add run secrects
perftool-incubator/workshop pull request #88
Opened 2024-12-05 02:34 UTC by atheurer

2025-01-24 21:47 UTC, k-rister requested changes
I think you're going to have to detect if `/run/secrets` exists and only map it if it does.

2025-01-27 21:22 UTC, k-rister commented
Hmm, kind of a weird error (IMHO) at https://github.com/perftool-incubator/workshop/actions/runs/12997155763/job/36247543444

2025-01-29 01:25 UTC, atheurer commented
At least one CI test is failing on a make install of trace-cmd:

```[ERROR] ################################################################################
[ERROR] COMMAND:         make -j32 install 2>&1
[ERROR] RETURN CODE:     2
[ERROR] COMMAND OUTPUT:
[ERROR] 
[ERROR] Have zlib compression support
[ERROR] Have ZSTD compression support
[ERROR]   UPDATE                 tracecmd_plugin_dir
[ERROR]   COMPILE FPIC           trace-filter-hash.o
[ERROR]   COMPILE FPIC           trace-hash.o
[ERROR] 
[ERROR]   COMPILE FPIC           trace-hooks.o
[ERROR]   COMPILE FPIC           trace-filter.o
[ERROR]   COMPILE FPIC           trace-rbtree.o
[ERROR]   COMPILE FPIC           trace-perf.o
[ERROR]   COMPILE FPIC           trace-input.o
[ERROR]   COMPILE FPIC           trace-recorder.o
[ERROR]   COMPILE FPIC           trace-maps.o
[ERROR]   COMPILE FPIC           trace-plugin.o
[ERROR]   COMPILE FPIC           trace-compress.o
[ERROR]   COMPILE FPIC           trace-compress-zlib.o
[ERROR]   COMPILE FPIC           trace-util.o
[ERROR]   COMPILE FPIC           trace-timesync-kvm.o
[ERROR]   COMPILE FPIC           trace-blk-hack.o
[ERROR]   COMPILE FPIC           trace-compress-zstd.o
[ERROR]   COMPILE FPIC           trace-output.o
[ERROR]   COMPILE FPIC           trace-timesync-ptp.o
[ERROR]   COMPILE FPIC           trace-msg.o
[ERROR]   COMPILE FPIC           trace-timesync.o
[ERROR]   COMPILE FPIC           trace-ftrace.o
[ERROR] make[1]: Nothing to be done for 'install_plugins'.
[ERROR]     NO_PYTHON forced: swig not installed, not compiling python plugins
[ERROR] 
[ERROR] make[1]: Nothing to be done for 'install_python'.
[ERROR]   INSTALL             trace-cmd.bash	to	/etc/bash_completion.d
[ERROR]   BUILD STATIC LIB       libtracecmd.a
[ERROR]   UPDATE                 tc_version.h
[ERROR]   COMPILE                trace-cmd.o
[ERROR]   COMPILE                trace-read.o
[ERROR]   COMPILE                trace-snapshot.o
[ERROR]   COMPILE                trace-profile.o
[ERROR]   COMPILE                trace-stream.o
[ERROR]   COMPILE                trace-split.o
[ERROR]   COMPILE                trace-check-events.o
[ERROR]   COMPILE                trace-stat.o
[ERROR]   COMPILE                trace-show.o
[ERROR]   COMPILE                trace-list.o
[ERROR]   COMPILE                trace-usage.o
[ERROR]   COMPILE                trace-dump.o
[ERROR]   COMPILE                trace-vm.o
[ERROR]   COMPILE                trace-convert.o
[ERROR]   COMPILE                trace-clear.o
[ERROR]   COMPILE                trace-attach.o
[ERROR]   COMPILE                trace-tsync.o
[ERROR]   COMPILE                trace-record.o
[ERROR]   COMPILE                trace-listen.o
[ERROR]   COMPILE                trace-stack.o
[ERROR]   COMPILE                trace-hist.o
[ERROR]   COMPILE                trace-restore.o
[ERROR]   COMPILE                trace-mem.o
[ERROR]   COMPILE                trace-setup-guest.o
[ERROR]   COMPILE                trace-sqlhist.o
[ERROR]   COMPILE                trace-vsock.o
[ERROR]   COMPILE                trace-agent.o
[ERROR] trace-profile.c:22:3: warning: #warning "lib audit not found, using raw syscalls " "(install audit-libs-devel(for fedora) or libaudit-dev(for debian/ubuntu) and try again)" [-Wcpp]
[ERROR]    22 | # warning "lib audit not found, using raw syscalls "    \
[ERROR]       |   ^~~~~~~
[ERROR]   BUILD                  trace-cmd
[ERROR] /usr/bin/ld: /root/trace-cmd-libtracecmd-1.5.1/tracecmd/trace-record.o: in function `find_ts':
[ERROR] /root/trace-cmd-libtracecmd-1.5.1/tracecmd/trace-record.c:4964:(.text+0xa6f5): undefined reference to `tep_find_field'
[ERROR] /usr/bin/ld: /root/trace-cmd-libtracecmd-1.5.1/tracecmd/trace-record.o: in function `get_ftrace_tep':
[ERROR] /root/trace-cmd-libtracecmd-1.5.1/tracecmd/trace-record.c:5005:(.text+0xa844): undefined reference to `tep_parse_header_page'
[ERROR] /usr/bin/ld: /root/trace-cmd-libtracecmd-1.5.1/tracecmd/trace-record.c:5013:(.text+0xa86f): undefined reference to `tep_free'
[ERROR] /usr/bin/ld: /root/trace-cmd-libtracecmd-1.5.1/tracecmd/trace-record.o: in function `get_date_to_ts':
[ERROR] /root/trace-cmd-libtracecmd-1.5.1/tracecmd/trace-record.c:5094:(.text+0xaa5e): undefined reference to `tep_free'
[ERROR] /usr/bin/ld: /root/trace-cmd-libtracecmd-1.5.1/tracecmd/trace-read.o: in function `print_event':
[ERROR] /root/trace-cmd-libtracecmd-1.5.1/tracecmd/trace-read.c:185:(.text+0x2f4): undefined reference to `tep_find_event_by_record'
[ERROR] /usr/bin/ld: /root/trace-cmd-libtracecmd-1.5.1/tracecmd/trace-read.c:186:(.text+0x327): undefined reference to `tep_print_event'
[ERROR] /usr/bin/ld: /root/trace-cmd-libtracecmd-1.5.1/tracecmd/trace-read.c:188:(.text+0x34e): undefined reference to `tep_print_event'
[ERROR] /usr/bin/ld: /root/trace-cmd-libtracecmd-1.5.1/tracecmd/trace-read.c:190:(.text+0x389): undefined reference to `tep_print_event'
[ERROR] /usr/bin/ld: /root/trace-cmd-libtracecmd-1.5.1/tracecmd/trace-read.o: in function `convert_comm_filter':
[ERROR] /root/trace-cmd-libtracecmd-1.5.1/tracecmd/trace-read.c:515:(.text+0x969): undefined reference to `tep_data_pid_from_comm'
[ERROR] /usr/bin/ld: /root/trace-cmd-libtracecmd-1.5.1/tracecmd/trace-read.c:521:(.text+0x9a3): undefined reference to `tep_cmdline_pid'
[ERROR] /usr/bin/ld: /root/trace-cmd-libtracecmd-1.5.1/tracecmd/trace-read.c:523:(.text+0x9e2): undefined reference to `tep_data_pid_from_comm'
[ERROR] /usr/bin/ld: /root/trace-cmd-libtracecmd-1.5.1/tracecmd/trace-read.o: in function `init_wakeup':
[ERROR] /root/trace-cmd-libtracecmd-1.5.1/tracecmd/trace-read.c:614:(.text+0xcad): undefined reference to `tep_find_event_by_name'
[ERROR] /usr/bin/ld: /root/trace-cmd-libtracecmd-1.5.1/tracecmd/trace-read.c:618:(.text+0xcda): undefined reference to `tep_find_field'
[ERROR] /usr/bin/ld: /root/trace-cmd-libtracecmd-1.5.1/tracecmd/trace-read.c:621:(.text+0xd02): undefined reference to `tep_find_field'
[ERROR] /usr/bin/ld: /root/trace-cmd-libtracecmd-1.5.1/tracecmd/trace-read.c:623:(.text+0xd1f): undefined reference to `tep_find_event_by_name'
[ERROR] /usr/bin/ld: /root/trace-cmd-libtracecmd-1.5.1/tracecmd/trace-read.c:627:(.text+0xd4c): undefined reference to `tep_find_field'
[ERROR] /usr/bin/ld: /root/trace-cmd-libtracecmd-1.5.1/tracecmd/trace-read.c:631:(.text+0xd74): undefined reference to `tep_find_field'
[ERROR] /usr/bin/ld: /root/trace-cmd-libtracecmd-1.5.1/tracecmd/trace-read.c:638:(.text+0xdab): undefined reference to `tep_find_event_by_name'
[ERROR] /usr/bin/ld: /root/trace-cmd-libtracecmd-1.5.1/tracecmd/trace-read.c:642:(.text+0xdd4): undefined reference to `tep_find_field'
[ERROR] /usr/bin/ld: /root/trace-cmd-libtracecmd-1.5.1/tracecmd/trace-read.c:645:(.text+0xdf8): undefined reference to `tep_find_field'
[ERROR] /usr/bin/ld: /root/trace-cmd-libtracecmd-1.5.1/tracecmd/trace-read.o: in function `process_wakeup':
[ERROR] /root/trace-cmd-libtracecmd-1.5.1/tracecmd/trace-read.c:743:(.text+0x10bc): undefined reference to `tep_data_type'
[ERROR] /usr/bin/ld: /root/trace-cmd-libtracecmd-1.5.1/tracecmd/trace-read.c:745:(.text+0x10e8): undefined reference to `tep_read_number_field'
[ERROR] /usr/bin/ld: /root/trace-cmd-libtracecmd-1.5.1/tracecmd/trace-read.c:749:(.text+0x1117): undefined reference to `tep_read_number_field'
[ERROR] /usr/bin/ld: /root/trace-cmd-libtracecmd-1.5.1/tracecmd/trace-read.c:753:(.text+0x1162): undefined reference to `tep_read_number_field'
[ERROR] /usr/bin/ld: /root/trace-cmd-libtracecmd-1.5.1/tracecmd/trace-read.c:757:(.text+0x1191): undefined reference to `tep_read_number_field'
[ERROR] /usr/bin/ld: /root/trace-cmd-libtracecmd-1.5.1/tracecmd/trace-read.c:762:(.text+0x11e7): undefined reference to `tep_read_number_field'
[ERROR] /usr/bin/ld: /root/trace-cmd-libtracecmd-1.5.1/tracecmd/trace-read.o:/root/trace-cmd-libtracecmd-1.5.1/tracecmd/trace-read.c:766: more undefined references to `tep_read_number_field' follow
[ERROR] /usr/bin/ld: /root/trace-cmd-libtracecmd-1.5.1/tracecmd/trace-read.o [...]

2025-01-29 15:00 UTC, k-rister approved these changes
There are some logging related cleanups I would like to do, but that can wait since I know these changes are needed.  I'll take care of that at some point.

2025-01-29 15:32 UTC, merged